#!/usr/bin/env bash

inherit() {
    (($# > 1)) || exit 1
    file="$1"
    shift
    while (($#)); do
        variable="$1"
        while IFS= read -r line; do
            if [[ $line == "$variable"=* ]]; then
                source /dev/stdin <<< "$line"
                break
            fi
        done < "$file"
        shift
    done
}

inherit "$@"
