#! /usr/bin/env -S -i PATH="${PATH}" bash --noprofile --norc -euo pipefail

case "$1" in
  "-s" | "--single")
    sed 's| |\n|g' <<< "${@:2}" | sed "s|\(.*\)|'\1'|g" | sort ;;
  *)
    sed 's| |\n|g' <<< "${@}"   | sed 's|\(.*\)|"\1"|g' | sort ;;
esac
