#!/usr/bin/env bash
set -euo pipefail

case "$1" in
  "-s" | "--single")
    shift
    printf "%s\n" "$@" | sed "s|\(.*\)|'\1'|g" | sort ;;
  *)
    printf "%s\n" "$@" | sed 's|\(.*\)|"\1"|g' | sort ;;
esac
